### ISSUE TITLE
Idea: Log Player total Playtime every X hours

### ISSUE THREAD

**Issue by Jpofin** [abrakadobr/dzsa-moreadminlogs#3]
Title.

It would be cool to have logs on how long a player has played in total on the server.
I plan on do a seasonal server with leaderboards and that's the only thing missing right now.

Overall good job, really looking forward of what you're planning to do in the future!

**Comment by abrakadobr** [comment]
Hey @Jpofin! Thanks for reaching :) 
This mod will not do any stats/leaderboards and other "nice things" - it's not mod purpose.
My plan for this mod - **to prepare** any kind of information, can be used later for different reasons - from leaderboards to anticheater tools.
I'm working in parallel on "visualization/stats" tool and all "nice things" would be there

I'll say in other way - my mod doesn't save any information anywhere (what is required for your idea), doesn't modify any databases, mechanics, players, items, infected or anything else - it only collect some "in moment" information, writes it into admin log and forget about it - all this required for mod to be compatible with most of other mods and be so fast as possible  (I'm ok with it's current working speed, there is no worries, but.. make fast a bit more faster - is always good ;) )
